version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - 8888:8888

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
