version: '3'
services:
  backend:
    platform: linux/amd64
    build:
      context: ./backend
    ports:
      - 8080:8080

  frontend:
    platform: linux/amd64
    build:
      context: ./frontend
    ports:
      - 3000:3000
