version: '3'
services:
  backend:
    container_name: code-server-backend-1
    platform: linux/amd64
    build:
      context: ./backend
    ports:
      - 8080:8080
    volumes:
      - code-server-volume:/home/shared

  frontend:
    container_name: code-server-frontend-1
    platform: linux/amd64
    build:
      context: ./frontend
    ports:
      - 3000:3000

volumes:
  code-server-volume: