version: '3'
services:
  backend:
    container_name: code-server-backend-1
    build:
      context: ./backend
    ports:
      - 8080:8080
    volumes:
      - code-server-volume:/home/shared

  frontend:
    container_name: code-server-frontend-1
    build:
      context: ./frontend
    ports:
      - 3000:3000

  backend-2:
    container_name: code-server-backend-2
    build:
      context: ./backend
    ports:
      - 8081:8081
    volumes:
      - code-server-volume:/home/shared

volumes:
  code-server-volume:
