version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - 3000:3000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    volumes:
      - ./frontend:/home/theia/workspace

